### ISSUE TITLE
[bug] 한/컴 변경내용 추적, 스크립트 실행 팝업 메세지 창으로 인한 자동화 불가 문제

### ISSUE THREAD

**Issue by KimYeonAh** [JJinTae/seleniumCrawler#2]
- 변경내용 추적 : 2020-12-04 일자 hwp 파일
   - 저장 버튼이 자동으로 눌려야 함 

- 스크립트 실행 : 2020-01-14 일자 hwp 파일
  - 취소 버튼이 자동으로 눌려야 함

**Comment by JJinTae** [comment]
한글 버전에 따른 문제가 있음
한글 2018 테스트 환경에서 적용되지 않음
한글 2014 테스트 환경에서 정상 작동 - 팝업 메시지 창 자동 스킵
